<?
/*
Copyright 2003-2012 John Vasko III

This file is part of Trade and Share.

Trade and Share is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Trade and Share is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Trade and Share.  If not, see <http://www.gnu.org/licenses/>.
*/

# Contents/Description: View box counterpart ?> 

<div id="motion">

<div class="title"><?
	if ($x['load']['motion']['name'] == 'edit' && $x['load']['view']['type'] == $x['load']['motion']['type'])
		$s1 = get_translation('page', $x['load']['view']['type'] . '_list');
	else
		$s1 = get_translation('page', $x['load']['motion']['type'] . '_' . $x['load']['motion']['name']);
	# uncomment if hybridizing user/contact pages
	/* switch ($x['load']['view']['type']) {
		case 'user':
		case 'contact':
			$s1 = 'Person';
			#$s1 = get_translation('page', 'contact_list') . ' (' . get_translation('page', 'user_list') . ')';
		break;
	} */ ?> 
	<span class="go_back"><?= print_go_back('&lt;&lt;'); ?></span>
	<h2><?= print_ts_focus($s1, 'motion'); ?></h2>
	<p class="result_add">
	<? if ($x['load']['motion']['name'] != 'set') {
	switch($x['load']['motion']['type']) {
		case 'user':
			if (!$key['user_id']['result'][   $data['view']['result']['listing'][0]['user_id']   ]['contact_id']) { ?> 
				<a href="./<?= ffm('list_name=list&list_type=contact&focus=&expand%5B0%5D=action&action_user_id=' . (int)get_gp('lock_user_id') . '&lock_user_id=' . (int)get_gp('lock_user_id'), 0); ?>"><?= tt('page', 'contact_list'); ?></a>*<?
			}
			else { ?> 
				<a href="./<?= ffm('list_name=list&list_type=contact&focus=&expand%5B0%5D=action', 0); ?>"><?= tt('page', 'contact_list'); ?></a>*<?
			}
		break;
		default:
			# todo hide message associated with the form on hiding that box. same as fast and quick
			$b1 = 1;
			if (isset($_GET['expand']))
			if (is_array($_GET['expand']))
			foreach ($_GET['expand'] as $k1 => $v1)
			if ($v1 == 'motion')
				$b1 = 2;
			?> 
			<a
				id="motion_el_swap1"
				style="display: <?= $b1 == 1 ? 'inline-block' : 'none'; ?>;"
				href="#"
				onclick="javascript: more_toggle_swap('motion_el', 'motion_el_swap2'); did('result').style.display = 'none'; return false;"
			><?= tt('element', 'edit'); ?></a>
			<a
				id="motion_el_swap2"
				style="display: <?= $b1 == 2 ? 'inline-block' : 'none'; ?>;"
				href="#" onclick="javascript: more_toggle_swap('motion_el', 'motion_el_swap1'); did('result').style.display = 'block'; return false;"
			><?= tt('element', 'list'); ?></a><?
			if (!empty($x['load']['view']['type'])) { ?> 
				<span style="margin-left: -5px;">*</span><?
			}
			/*
			# previous unchanging text ?> 
			<a href="javascript: more_toggle('motion_el_box');"><?= tt('element', 'edit'); ?><span id="motion_el_box_toggle" style="display: none;"> <?= $x['part'][1] == 'edit' ? tt('element', 'less') : tt('element', 'more'); ?></span></a>*
			<?
			*/
		break;
	} } ?> 
	</p>
</div><?

if ($x['preload']['focus'] == 'motion')
	print_message_bar();

# motion box start ?> 
<span id="motion_el_box"  style="display: <?= get_motion_style_display(); ?>;">
<div class="content">
<form name="motion_process" action="/index.php" method="POST">
<input type="hidden" name ="x" value="<?= to_html($x['.']); ?><?= $x['load']['motion']['name']; ?>_process/" />
<input type="hidden" name="q" value="<?= ff('', 1); ?>" />
<input type="hidden" name="load" value="motion" />
<input type="hidden" name="type" value="<?= $x['load']['motion']['type']; ?>" />
<input type="hidden" name="id" value="<?= (int)$x['load']['motion']['id']; ?>" />
<?

# todo make it so repeating login from action_content isnt necessary 2012-05-01 vaskoiii
if (!empty($data['motion']['response'])) {
foreach($data['motion']['response'] as $k1 => $v1) {
if (!empty($v1)) {
foreach($v1 as $k2 => $v2) {
switch($k2) {
	case 'accept_friend':
	case 'accept_usage_policy':
	case 'feature_lock':
	case 'feature_minnotify':
	case 'load_javascript':
	case 'notify_offer_received':
	case 'notify_teammate_received':
	case 'remember_login':
		# dont override checkboxes
	break;
	// Special variable ONLY used on invitation!
	case 'invite_user_name':
	case 'invite_password':
		if (isset_gp('edit_id') || $x['page']['name'] == 'invite_edit')  // password is autogenerated and uneditable 2008-12-04
			unset($data['motion']['response']['motion_content_1'][$k2]);
	break;
	case 'user_name':
	case 'lock_user_name':
	case 'contact_name':
	case 'lock_contact_name':
		// do nothing.
	break;
	default:
		//if (!empty($v2) { ?> 
			<input type="hidden" name="<?= to_html($k2); ?>" value="<?= to_html($v2); ?>" /><?
		//}
	break;
} } } } } ?> 
<div class="table">
	<div id="motion_content_1"><?
		print_container($motion_content_1, $motion_listing, $key, $translation, 'motion'); ?> 
	</div><?

	if(!empty($motion_content_2)) { ?> 
	<p class="more_solo">
		&gt;&gt; <a id="motion_content_2_toggle" style="display: inline;" href="#" onclick="more_toggle('motion_content_2'); return false;"><?= tt('element', 'more'); ?></a>
	</p><?
	} ?> 
	<div id="motion_content_2" style="margin-left: 20px; margin-bottom: 15px; display: none;"><?
		print_container($motion_content_2, $motion_listing, $key, $translation, 'motion'); ?> 
	</div>
</div>

<div class="menu_1">
<ul><?
if (!empty($data['motion']['response']['motion_footer_1'])) {
foreach($data['motion']['response']['motion_footer_1'] as $k1 => $v1) {
switch($k1) {
	case 'add':
	if ($x['preload']['preview'] != 'motion') {
	if (!$x['load']['motion']['id']) { ?> 
		<input type="submit" name="<?= $k1; ?>" value="<?= tt('element', $k1); ?>" /><?
	} }
	break;
	case 'edit':
	if ($x['preload']['preview'] != 'motion') {
	if ($x['load']['motion']['id']) { ?> 
		<input type="submit" name="<?= $k1; ?>" value="<?= tt('element', $k1); ?>" /><?
	} }
	break;
} } } ?> 
</ul>
</div>

<div class="menu_2">
<ul><?
if ($x['preload']['preview'] == 'motion') { ?> 
	<li><a href="#"><?= tt('element', 'reedit'); ?></a></li><?
} ?> 
</ul>
</div>

</form>
</div>
</span><?
# motion box end ?> 
</div>
